### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by ganlanyuan** [on2-dev/share-api-polyfill#96]
Which browser does it support?
Seems it doesn't work on IE 11-, Chrome 40-. How can I make it work for these browsers?

**Comment by syonfox** [comment]
It works on Linux chrome and Firefox for me

**Comment by rsip22** [comment]
> Which browser does it support? Seems it doesn't work on IE 11-, Chrome 40-. How can I make it work for these browsers?

Hello, ganlanyuan!

This Polyfill relies on the navigator.share() method of the Web Share API. CanIUse has a table of the browsers which support it: https://caniuse.com/?search=navigator.share.

It seems a bit outdated since this Polyfill certainly works out of the box with current versions of Firefox, but I hope this is enough to give you a rough idea.
